" 显示行号
set number
" 显示标尺
set ruler
" 历史纪录
set history=1000
" 输入的命令显示出来，看的清楚些
set showcmd
" 状态行显示的内容
set statusline=%F%m%r%h%w\ [FORMAT=%{&ff}]\ [TYPE=%Y]\ [POS=%l,%v][%p%%]\ %{strftime(\"%d/%m/%y\ -\ %H:%M\")}
" 启动显示状态行1，总是显示状态行2
set laststatus=2
" 语法高亮显示
syntax on
set fileencodings=utf-8,gb2312,gbk,cp936,latin-1
set fileencoding=utf-8
set termencoding=utf-8
set fileformat=unix
set encoding=utf-8
" 配色方案
colorscheme desert
" 指定配色方案是256色
set t_Co=256

set wildmenu

" 去掉有关vi一致性模式，避免以前版本的一些bug和局限，解决backspace不能使用的问题
set nocompatible
set backspace=indent,eol,start
set backspace=2

" 启用自动对齐功能，把上一行的对齐格式应用到下一行
set autoindent

" 依据上面的格式，智能的选择对齐方式，对于类似C语言编写很有用处
set smartindent

" vim禁用自动备份
set nobackup
set nowritebackup
set noswapfile

" 用空格代替tab
set expandtab

" 设置显示制表符的空格字符个数,改进tab缩进值，默认为8，现改为4
set tabstop=4

" 统一缩进为4，方便在开启了et后使用退格(backspace)键，每次退格将删除X个空格
set softtabstop=4

" 设定自动缩进为4个字符，程序中自动缩进所使用的空白长度
set shiftwidth=4

" 设置帮助文件为中文(需要安装vimcdoc文档)
set helplang=cn

" 显示匹配的括号
set showmatch

" 文件缩进及tab个数
au FileType html,python,vim,javascript setl shiftwidth=4
au FileType html,python,vim,javascript setl tabstop=4
au FileType java,php setl shiftwidth=4
au FileType java,php setl tabstop=4
" 高亮搜索的字符串
set hlsearch

" 检测文件的类型
filetype on
filetype plugin on
filetype indent on

" C风格缩进
set cindent
set completeopt=longest,menu

" 功能设置

" 去掉输入错误提示声音
set noeb
" 自动保存
set autowrite
" 突出显示当前行 
set cursorline
" 突出显示当前列
set cursorcolumn
"设置光标样式为竖线vertical bar
" Change cursor shape between insert and normal mode in iTerm2.app
"if $TERM_PROGRAM =~ "iTerm"
let &t_SI = "\<Esc>]50;CursorShape=0\x7" " Vertical bar in insert mode
let &t_EI = "\<Esc>]50;CursorShape=0\x7" " Block in normal mode
"endif
" 共享剪贴板
set clipboard+=unnamed
" 文件被改动时自动载入
set autoread
" 顶部底部保持3行距离
set scrolloff=3

" vundle
filetype off
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" plugins begin
Plugin 'VundleVim/Vundle.vim'
Plugin 'scrooloose/nerdtree'
Plugin 'vim-syntastic/syntastic'
"Plugin 'godlygeek/tabular'
Plugin 'Shougo/neocomplcache.vim'
"文件搜索
Plugin 'kien/ctrlp.vim'
Plugin 'terryma/vim-multiple-cursors'
"自动匹配
Plugin 'jiangmiao/auto-pairs'
Plugin 'vimagit'
Plugin 'bling/vim-airline'
"主题（无效）
Plugin 'vim-airline/vim-airline-themes'
"提示
Plugin 'quickfixsigns'
"文件结构，函数名、变量
Plugin 'tagbar'
"Plugin 'DoxygenToolkit'
" go 插件
Plugin 'fatih/vim-go'
Plugin 'Valloric/YouCompleteMe'
Plugin 'Xuyuanp/nerdtree-git-plugin'
" plugins end
call vundle#end()
filetype plugin indent on


"Plugin 'quickfixsigns' config
noremap <silent> <leader><c-l> :call quickfixsigns#RelNumbersOnce()

set foldenable              " 开始折叠
set foldmethod=indent       " 设置语法折叠
set foldcolumn=1           " 设置折叠区域的宽度
setlocal foldlevel=1        " 设置折叠层数为
"set foldlevelstart=99       " 打开文件是默认不折叠代码


function! CurDir()
    let curdir = substitute(getcwd(), '/Users/Vingel/', "~/", "g")
    return curdir
endfunction

"" cscope config
if has("cscope")
    set csprg=/usr/local/bin/cscope
    set csto=0
    set cst
    set nocsverb
    let $curDir=CurDir()
    if filereadable("cscope.out")
        cs add cscope.out $curDir
    elseif $CSCOPE_DB != ""
        cs add $CSCOPE_DB
    endif
    set csverb
endif

set cscopequickfix=s-,c-,d-,i-,t-,e-

map lc :lclose<CR>
map ns :cnext<CR>
map ps :cpre<CR>

map <S-j> :resize +3 <CR>
map <S-k> :resize -3 <CR>
map <S-l> :vertical resize -3<CR>
map <S-h> :vertical resize +3 <CR>


let g:DoxygenToolkit_authorName="cloudsky <wzx_1987@163.com>"
let s:licenseTag = "Copyright(C)\<enter>"
let s:licenseTag = s:licenseTag . "For free\<enter>"
let s:licenseTag = s:licenseTag . "All right reserved\<enter>"
let g:DoxygenToolkit_licenseTag = s:licenseTag
let g:DoxygenToolkit_briefTag_funcName="yes"
let g:doxygen_enhanced_color=1

map  <C-t> :Dox<CR>
map  <C-r> :DoxAuthor<CR>
map  <C-e> :NERDTreeToggle<CR>

" 文件大纲
map <S-l> :TagbarToggle<CR>


""""""" 文件列表 """"""
" 显示行号
let NERDTreeShowLineNumbers=1
let NERDTreeAutoCenter=1
" 是否显示隐藏文件
let NERDTreeShowHidden=1
" 设置宽度
let NERDTreeWinSize=31
" 在终端启动vim时，共享NERDTree
let g:nerdtree_tabs_open_on_console_startup=1
" 忽略一下文件的显示
let NERDTreeIgnore=['\.pyc','\~$','\.swp']
" 显示书签列表
let NERDTreeShowBookmarks=1"

let g:NERDTreeIndicatorMapCustom = {
            \"Modified"  : "✹",
            \"Staged"    : "✚",
            \"Untracked" : "✭",
            \"Renamed"   : "➜",
            \"Unmerged"  : "═",
            \"Deleted"   : "✖",
            \"Dirty"     : "✗",
            \"Clean"     : "✔︎",
            \"Unknown"   : "?"
            \}

